### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by glenjamin** [skybet/amqpea#13]
Not sure why, don't have time to find out right now: https://travis-ci.org/skybet/amqpea

The code hasn't changed, so must be environmental.

**Comment by tomnomnom** [comment]
It's the longjohn version. 0.2.7 seemed to work fine, but 0.2.10 doesn't.

Fixed in 7c17674a6436a05160e11dcf1b856aebdb373a92

**Comment by glenjamin** [comment]
Nice one, did you already know that from internal use, or bisect something?

**Comment by tomnomnom** [comment]
Nope; not actually using amqpea - cloned it specially to fix it when I saw the breakage :)

I just compared the two travis runs' output.
