### ISSUE TITLE
Buffer error connecting to ActiveMQ docker container

### ISSUE THREAD

**Issue by mark-r-m** [skybet/amqpea#14]
## Docker command for my container:
- Assume docker running on 192.168.123.123 in OracleBox. 
- `docker run --name data-activemq -p 1883:1883 -p 5672:5672 -p 8161:8161 -p 61613:61613 -p 61614:61614 -p 61616:61616 -e 'ACTIVEMQ_MIN_MEMORY=512' -e 'ACTIVEMQ_MAX_MEMORY=2048' -v $DATA_PATH/activemq:/data/activemq -h data-activemq -d webcenter/activemq:5.12.0`
## Connection url used:
- See the all-in-one example from your page https://www.npmjs.com/package/amqpea
- `var targetUri = 'amqp://guest:guest@192.168.123.123:61616/%2F';`
## Errors received:

$ node ActiveMQ-AmqPea-Pub-Sub.js 

``` javascript
--connect-- 
... targetUri = amqp://guest:guest@192.168.123.123:61616/%2F 
--die-- 
C:\git\queue-demo\ActiveMQ-AmqPea-Pub-Sub.js:58 
throw err; 
^ 
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes 
at new Buffer (buffer.js:71:11) 
at FrameParser.parseFrameStart (C:\git\queue-demo\node_modules\amqpea\node_modules\bramqp\lib\frameParser.js:367:29) 
at FrameParser.parse (C:\git\queue-demo\node_modules\amqpea\node_modules\bramqp\lib\frameParser.js:433:57) 
at Socket.<anonymous> (C:\git\queue-demo\node_modules\amqpea\node_modules\bramqp\lib\connectionHandle.js:54:22) 
at Socket.g (events.js:199:16) 
at Socket.emit (events.js:107:17) 
at readableAddChunk (_stream_readable.js:163:16) 
at Socket.Readable.push (_stream_readable.js:126:10) 
at TCP.onread (net.js:538:20)
```

**Comment by mark-r-m** [comment]
The same happens connecting to port 5672
- var targetUri = 'amqp://guest:guest@cip-data-activemq:5672/%2F';

**Comment by mark-r-m** [comment]
And for reference;
- http://activemq.apache.org/amqp.html

**Comment by glenjamin** [comment]
I've never used this with ActiveMQ, only rabbit - but in theory it should work.

Can you run your script with debug mode enabled by setting the environment variable `NODE_DEBUG_AMQP=1`?

It looks like ActiveMQ is sending a gigantic packet and the node binary packet system it rejecting it.

**Comment by mark-r-m** [comment]
Sure thing - I get this;

``` javascript
$ export NODE_DEBUG_AMQP=1; node ActiveMQ-AmqPea-Pub-Sub.js
--connect--
... targetUri = amqp://guest:guest@cip-data-activemq:5672/%2F
1:AMQP Connecting to cip-data-activemq:5672
1:AMQP Socket connected to cip-data-activemq:5672
1:AMQP listener attached for "connection.start"
--die--
C:\git\queue-demo\ActiveMQ-AmqPea-Pub-Sub.js:58
    throw err;
          ^
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
    at new Buffer (buffer.js:71:11)
    at FrameParser.parseFrameStart (C:\git\queue-demo\node_modules\amqpea\node_modules\bramqp\lib\frameParser.js:367:29)
    at FrameParser.parse (C:\git\queue-demo\node_modules\amqpea\node_modules\bramqp\lib\frameParser.js:433:57)
    at Socket.<anonymous> (C:\git\queue-demo\node_modules\amqpea\node_modules\bramqp\lib\connectionHandle.js:54:22)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by mark-r-m** [comment]
Here's my entire script:

``` javascript
var amqpea = require('amqpea');

//url is amqp://login:password@hostname:port/vhost
var targetUri = 'amqp://guest:guest@192.168.123.123:5672/%2F';

console.log('--connect--');
console.log('... targetUri = ' + targetUri);
var amqp = amqpea(targetUri, { timeout: 2000 });

amqp.on('error', die);

amqp.on('ready', function() {
    console.log('--on ready--');
    amqp.declareExchange({
        name: 'my_exchange_name'
    }, whenExchangeReady);
});

function whenExchangeReady(err) {
    console.log('--whenExchangeReady--');
    if (err) return die(err);
    amqp.declareQueue({
        name: 'my_queue_name',
        exclusive: true,
        binding: {
            exchange: 'my_exchange_name',
            keys: ['route']
        }
    }, whenQueueReady);
};

function whenQueueReady(err) {
    console.log('--whenQueueReady--');
    if (err) return die(err);
    beginPublishing();
    var consumer = amqp.createQueueConsumerChannel('my_queue_name', 1);
    consumer.consume('ack', 'exclusive', function(msg) {
        var body = msg.fromJSON();
        console.log("Received: %j", body);
        msg.ack();
    });
};

function beginPublishing() {
    console.log('--beginPublishing--');
    var i = 0;
    var publisher = amqp.createPublishChannel('confirm');
    setInterval(function() {
        publisher.publish('my_exchange_name', 'route', { num: ++i }, function(err) {
            if (err) return die(err);
            console.log("Published message %d", i);
        });
    }, 1000);
};

function die(err) {
    console.log('--die--');
    throw err;
};

```

**Comment by glenjamin** [comment]
That definitely seems to be very early in the handshake, could you try using https://github.com/bakkerthehacker/bramqp directly to connect and see if you get the same error?

From looking at the line in the stack trace: https://github.com/bakkerthehacker/bramqp/blob/master/lib/frameParser.js#L367 it seems ActiveMQ is reporting the frame packet size to be gigantic.

**Comment by mark-r-m** [comment]
I'll give that a try... 
- https://github.com/bakkerthehacker/bramqp/tree/master/tutorial/1%20Hello%20World

**Comment by mark-r-m** [comment]
So the brampq guys checked it out for me - it turns out that the AMQP 0.9.x and 1.0.0 specs are quite different - and RabbitMQ supports 0.9.X and ActiveMQ supports 1.0, and there probably aren't any node libraries that support both versions. So effectively - you have to choose between different stacks.
See https://github.com/bakkerthehacker/bramqp/issues/45

**Comment by glenjamin** [comment]
Ah, I see - I should have clicked the original ActiveMQ link - I'd have spotted that right away.

I wouldn't recommend AMQP 1.0 - they've ruined a perfectly good specification in my opinion.
